CREATE TABLE IF NOT EXISTS QUOTES(
    id UUID PRIMARY KEY,
    quote_text VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    user_id UUID REFERENCES USERS(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
